kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
   name: portworx-sc
   annotations:
{{- if .Values.storageclass.isDefault }}
     storageclass.kubernetes.io/is-default-class: "true"
{{- end }}
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
